export const ACTION_TYPE = {
  ADD_INGREDIENTS: "ADD_INGREDIENTS",
  REMOVE_INGREDIENTS: "REMOVE_INGREDIENTS",
  SET_INGREDIENTS: "SET_INGREDIENTS",
  FETCH_INGREDIENTS_FAIL: "FETCH_INGREDIENTS_FAIL",

  PURCHASE_BURGET_SUCCESS: "PURCHASE_BURGET_SUCCESS",
  PURCHASE_BURGET_FAILURE: "PURCHASE_BURGET_FAILURE ",
  PURCHASE_BURDER: "PURCHASE_BURDER",
  PURCHASE_INIT: "PURCHASE_INIT",

  ORDER_LIST_SUCCESS: "ORDER_LIST_SUCCESS",
  ORDER_LIST_FAILURE: "ORDER_LIST_FAILURE ",
  FETCH_ORDER_LIST: "FETCH_ORDER_LIST",
  FETCH_ORDER_INIT: "FETCH_ORDER_INIT",
};
